// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongRecommendAPI.Infra;

namespace SongRecommendAPI.Migrations
{
    [DbContext(typeof(SongRecommendContext))]
    [Migration("20190509151136_datenullable")]
    partial class datenullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SongRecommendAPI.Model.BaseWord", b =>
                {
                    b.Property<string>("Word")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<double>("NegativePoint");

                    b.Property<double>("PositivePoint");

                    b.Property<double?>("Rate");

                    b.HasKey("Word");

                    b.ToTable("BaseWord");
                });

            modelBuilder.Entity("SongRecommendAPI.Model.BaseWordCollectingSong", b =>
                {
                    b.Property<int>("SongId");

                    b.Property<bool?>("IsPositive");

                    b.Property<string>("Lyric")
                        .HasColumnType("NTEXT");

                    b.Property<string>("Message")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<int>("PlayListSeq");

                    b.Property<double?>("Rate");

                    b.Property<string>("Singer")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR(1000)");

                    b.HasKey("SongId");

                    b.ToTable("BaseWordCollectingSong");
                });

            modelBuilder.Entity("SongRecommendAPI.Model.ProposeSong", b =>
                {
                    b.Property<int>("SongId");

                    b.Property<DateTime>("AddDate");

                    b.Property<string>("Genre")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<int>("Like");

                    b.Property<string>("Lyric")
                        .HasColumnType("NTEXT");

                    b.Property<int>("PlayListSeq");

                    b.Property<double>("Rate");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<string>("Singer")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR(1000)");

                    b.HasKey("SongId");

                    b.ToTable("ProposeSong");
                });
#pragma warning restore 612, 618
        }
    }
}
